name: ItemID
main: com.lonelydime.ItemId.ItemId
version: 1.2.1
website: https://github.com/lonelydime
author: lonelydime
description: >
             Get the ids of items.
commands:
    itemid:
        description: Returns the data id or data name given the item name or id, respectively.
        usage: /<command> [item id or name]
    find:
        description: Search for items and blocks
        usage: /<command> [search query]
permissions:
    itemid.*:
        description: Gives access to all commands
        children:
            itemid.usecmd: true
            itemid.find: true
    itemid.usecmd:
        description: Allows usage of /itemid
        default: true
    itemid.find:
        description: Allows usage of /find
        default: true